version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    tmpfs:
      - /tmp
    restart: unless-stopped
    environment:
      - GIN_MODE=release
