name: build-docker

env:
  YAMLPATH: clusters/us-rockies-1/apps/trmnl/app/helmrelease.yaml

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
      - 'v*.*'

jobs:

  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/rmitchellscott/trmnl-2bit-demo
          tags: |
            # branch-based tags (e.g. 'main')
            type=ref,event=branch

            # mirror git tag (e.g. 'v1.2.3')
            type=ref,event=tag

            # semver without the 'v' (e.g. '1.2.3')
            type=semver,pattern={{version}}

            # major.minor (e.g. '1.2')
            type=semver,pattern={{major}}.{{minor}}

            # major only (e.g. '1')
            type=semver,pattern={{major}}

            # latest on main
            type=raw,priority=1000,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}

            # commit short SHA
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          pull: true
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    runs-on: ubuntu-latest
    name: Deploy via flux
    needs: build
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out Kubernetes repo
        uses: actions/checkout@v4
        with:
          repository: rmitchellscott/fleet-infra
          token: ${{ secrets.PAT }}
      
      - name: Set deployment tag
        id: set-tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            # For tags, use the version without 'v' prefix
            TAG="${GITHUB_REF#refs/tags/}"
            TAG="${TAG#v}"
            echo "tag=${TAG}" >> $GITHUB_OUTPUT
          else
            # For branches, use sha-<short_sha> format
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            echo "tag=sha-${SHORT_SHA}" >> $GITHUB_OUTPUT
          fi
      
      - name: Bump version
        uses: clevyr/yampl-action@v1
        with:
          file: ${{env.YAMLPATH}}
          values: |
            tag=${{ steps.set-tag.outputs.tag }}
          commit_message: ":arrow_up: Bump ${{ github.event.repository.name }} to ${{ steps.set-tag.outputs.tag }}"
